name: Debug Action

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true
      pr_filter:
        description: 'Filter PRs'
        required: true
        type: choice
        options:
          - 'all'
          - 'labelled'
          - 'error'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug Action
        uses: ./
        with:
          github_token: ${{ github.event.inputs.github_token }}
          pr_filter: ${{ github.event.inputs.pr_filter }}
          pr_label: 'autoupdate'
          pr_ready_state: 'all'
          exclude_pr_label: ''
          merge_conflict_action: 'fail'
          merge_method: 'merge'
          merge_commit_message: ''

          